name: Network
description: For Network
title: "[Network]: "
labels: ["Network"]
assignees:
  - Jack-R-lantern
body:
  - type: markdown
    attributes:
      value: |
        Network 학습과 관련된 이슈를 작성해주세요.
  - type: dropdown
    attributes:
      label: Network Service
      description: "학습할 Network를 선택해주세요."
      multiple: true
      options:
        - VPC
        - Route53
        - CloudFront
        - ELB
    validations:
      required: true
  - type: textarea
    attributes:
      label: Task List
    validations:
      required: true